import os
import uuid
import json
from ..schemas import PPTContent

def create_html_presentation(content: PPTContent) -> str:
    """
    Generates a standalone HTML file using Reveal.js CDN.
    """
    slides_html = ""
    
    # Title Slide
    slides_html += f"""
    <section style="background-color: {content.theme_color}; color: #fff;">
        <h1 style="color: #fff; font-size: 3.5em; margin-bottom: 20px;">{content.title}</h1>
        <div style="width: 100px; height: 6px; background-color: {content.accent_color}; margin: 0 auto 40px;"></div>
        <p style="opacity: 0.8; font-size: 1.2em;">Generated by GenPPT AI Designer</p>
    </section>
    """
    
    # Content Slides
    for slide in content.slides:
        is_centered = slide.layout_type == 'centered'
        is_two_columns = slide.layout_type == 'two_columns'
        
        title_style = f"color: {content.theme_color}; font-weight: bold; margin-bottom: 50px; font-size: 2.8em; line-height: 1.2;"
        if is_centered:
            title_style += " text-align: center;"
        else:
            title_style += " text-align: left;"
            
        slides_html += f'<section class="slide-content" style="text-align: left; padding: 60px 80px; height: 100%; box-sizing: border-box; display: flex; flex-direction: column;">'
        slides_html += f'<h2 style="{title_style}">{slide.page_title}</h2>'
        
        slides_html += '<div style="flex: 1; display: flex; flex-direction: column; justify-content: flex-start; overflow: hidden;">'
        
        if is_two_columns:
            slides_html += '<div style="display: flex; gap: 60px; align-items: flex-start; height: 100%;">'
            slides_html += '<div style="flex: 1; overflow-y: auto;">'
            slides_html += '<ul style="font-size: 0.9em; line-height: 1.7; font-weight: 500;">'
            for point in slide.content:
                slides_html += f'<li style="margin-bottom: 25px; color: #333;">{point}</li>'
            slides_html += '</ul></div>'
            
            slides_html += f"""
            <div style="flex: 1; height: 85%; background: #fcfcfc; border: 2px dashed #ddd; border-radius: 20px; padding: 30px; text-align: center; color: #999; font-style: italic; display: flex; align-items: center; justify-content: center; box-shadow: inset 0 2px 10px rgba(0,0,0,0.02);">
                <div><span style="font-size: 2em; display: block; margin-bottom: 10px;">🖼️</span>[Visual Placeholder]<br/><small style="display: block; margin-top: 10px; line-height: 1.4;">{slide.image_description or "No image suggested"}</small></div>
            </div>
            """
            slides_html += '</div>'
        elif is_centered:
            slides_html += '<div style="text-align: center; margin-top: 40px;">'
            slides_html += '<ul style="list-style: none; font-size: 1.3em; line-height: 1.8; display: inline-block; text-align: center; padding: 0; font-weight: 500;">'
            for point in slide.content:
                slides_html += f'<li style="margin-bottom: 20px; color: #333;">{point}</li>'
            slides_html += '</ul></div>'
        else:
            slides_html += '<div style="overflow-y: auto;">'
            slides_html += '<ul style="font-size: 1.1em; line-height: 1.7; margin-left: 50px; font-weight: 500;">'
            for point in slide.content:
                slides_html += f'<li style="margin-bottom: 25px; color: #333;">{point}</li>'
            slides_html += '</ul></div>'
            
        slides_html += '</div>' # end flex:1 container
            
        if slide.image_description and not is_two_columns:
            slides_html += f"""
            <div style="margin-top: auto; padding: 15px 20px; background: #fcfcfc; border-left: 6px solid {content.accent_color}; font-size: 0.6em; color: #666; font-style: italic; border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,0.04);">
                <strong style="color: {content.theme_color}; margin-right: 10px; font-style: normal;">🎨 设计建议:</strong> {slide.image_description}
            </div>
            """
            
        slides_html += '</section>'

    html_template = f"""
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="utf-8">
    <title>{content.title}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/reveal.js@4.5.0/dist/reset.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/reveal.js@4.5.0/dist/reveal.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/reveal.js@4.5.0/dist/theme/white.css">
    <style>
        :root {{
            --r-main-font-size: 32px;
        }}
        .reveal .slides section {{
            height: 100%;
            padding: 0;
        }}
        .reveal h1, .reveal h2, .reveal h3 {{
            text-transform: none;
        }}
        .slide-content li {{
            margin-bottom: 10px;
        }}
        /* Ensure content doesn't overflow */
        .slide-content {{
            box-sizing: border-box;
        }}
    </style>
</head>
<body>
    <div class="reveal">
        <div class="slides">
            {slides_html}
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/reveal.js@4.5.0/dist/reveal.js"></script>
    <script>
        Reveal.initialize({{
            width: 1200,
            height: 800,
            margin: 0.05,
            minScale: 0.2,
            maxScale: 2.0,
            hash: true,
            center: true,
            transition: 'slide',
            controls: true,
            progress: true,
            mouseWheel: true
        }});
    </script>
</body>
</html>
    """
    
    filename = f"presentation_{uuid.uuid4()}.html"
    output_dir = os.path.join(os.getcwd(), "backend", "generated_ppts")
    os.makedirs(output_dir, exist_ok=True)
    file_path = os.path.join(output_dir, filename)
    
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(html_template)
        
    return filename
