import os
import uuid
import json
import html
import urllib.parse
from ..schemas import PPTContent

def get_background_css(bg_style: str, theme_color: str, accent_color: str) -> str:
    if bg_style == "gradient":
        return f"background: linear-gradient(135deg, {theme_color} 0%, {accent_color} 100%);"
    elif bg_style == "mesh":
        return f"""
        background-color: {theme_color};
        background-image: 
            radial-gradient(at 40% 20%, {accent_color} 0px, transparent 50%),
            radial-gradient(at 80% 0%, {theme_color} 0px, transparent 50%),
            radial-gradient(at 0% 50%, {theme_color} 0px, transparent 50%);
        """
    else:
        return f"background-color: {theme_color};"

def _safe_text(value) -> str:
    if value is None:
        return ""
    return html.escape(str(value), quote=True)

def create_html_presentation(content: PPTContent) -> str:
    """
    Generates a standalone HTML file using Reveal.js CDN with modern Vibe design.
    """
    slides_html = ""
    
    # Check if we should use light text based on theme color brightness
    # A simple heuristic: if it's not a very light color, use white text for the main cover
    
    bg_css = get_background_css(content.bg_style, content.theme_color, content.accent_color)
    safe_title = _safe_text(content.title)
    safe_subtitle = _safe_text(content.subtitle)
    
    # Title Slide (Vibe Style)
    slides_html += f"""
    <section style="{bg_css} color: #ffffff; position: relative; overflow: hidden;" class="vibe-slide">
        <div style="position: absolute; top: 0; left: 0; right: 0; bottom: 0; background: rgba(0,0,0,0.2);"></div>
        <div class="vibe-slide-inner" style="position: relative; z-index: 10;">
            <h1 class="animate-fade-up" style="color: #ffffff; font-size: 4.5em; font-weight: 800; margin-bottom: 20px; line-height: 1.1; letter-spacing: -0.02em; text-shadow: 0 10px 30px rgba(0,0,0,0.3); text-align: left;">
                {safe_title}
            </h1>
            {f'<p class="animate-fade-up" style="font-size: 1.8em; color: rgba(255,255,255,0.9); text-align: left; margin-bottom: 40px; font-weight: 300; animation-delay: 0.2s;">{safe_subtitle}</p>' if content.subtitle else ''}
            <div class="animate-width" style="width: 80px; height: 6px; background-color: {content.accent_color}; border-radius: 3px; box-shadow: 0 0 20px {content.accent_color}; animation-delay: 0.5s;"></div>
            <p class="animate-fade-up" style="margin-top: 60px; text-align: left; font-size: 1em; color: rgba(255,255,255,0.5); font-family: monospace; letter-spacing: 0.1em; text-transform: uppercase; animation-delay: 0.8s;">
                GENERATED BY GENPPT VIBE AI
            </p>
        </div>
    </section>
    """
    
    # Content Slides
    for slide in content.slides:
        l_type = (slide.layout_type or "").lower().replace("-", "_").replace(" ", "_")
        safe_page_title = _safe_text(slide.page_title)
        safe_slide_subtitle = _safe_text(slide.subtitle)
        safe_image_desc = _safe_text(slide.image_description or "")
        
        # Check if content is effectively empty
        # We need to handle potential None values gracefully AND empty string arrays
        is_empty_content = False
        if not slide.content or len(slide.content) == 0:
            is_empty_content = True
        elif len(slide.content) == 1:
            item = slide.content[0]
            # Handle if item is a dictionary
            if isinstance(item, dict):
                if not item.get("title", "") and not item.get("description", ""):
                    is_empty_content = True
            # Handle if item is a Pydantic model or object
            elif hasattr(item, "title"):
                if not getattr(item, "title", "") and not getattr(item, "description", ""):
                    is_empty_content = True
            # Handle if item is just an empty string
            elif isinstance(item, str) and not item.strip():
                is_empty_content = True
                
        is_title_only = "title" in l_type or l_type == "cover" or is_empty_content
        is_timeline = "time" in l_type or "step" in l_type
        is_content_list = "list" in l_type or "two" in l_type or "column" in l_type
        
        # Determine slide background (mostly light for readability, or subtle gradient)
        slide_bg = f"background: radial-gradient(circle at top right, rgba(255,255,255,1) 0%, #f8f9fa 100%);"
        
        if is_title_only:
            # Special high-impact slide
            slides_html += f"""
            <section style="{bg_css} color: white;" class="vibe-slide transition-slide">
                <div class="vibe-slide-inner">
                    <h2 class="animate-scale" style="color: white; font-size: 4em; font-weight: 800; line-height: 1.2; text-shadow: 0 10px 30px rgba(0,0,0,0.2);">{safe_page_title}</h2>
                    {f'<p class="animate-fade-up" style="color: rgba(255,255,255,0.8); font-size: 1.5em; margin-top: 30px; animation-delay: 0.3s;">{safe_slide_subtitle}</p>' if slide.subtitle else ''}
                </div>
            </section>
            """
            continue
            
        slides_html += f'<section class="slide-content vibe-content-slide" style="{slide_bg} text-align: left;">'
        slides_html += '<div class="vibe-content-inner">'
        
        # Header Area
        slides_html += f"""
        <div style="margin-bottom: 40px;">
            <h2 class="animate-fade-right" style="color: {content.theme_color}; font-weight: 800; font-size: 3em; line-height: 1.1; margin-bottom: 10px; letter-spacing: -0.01em;">{safe_page_title}</h2>
            {f'<p class="animate-fade-right" style="color: #64748b; font-size: 1.2em; font-weight: 500; animation-delay: 0.2s;">{safe_slide_subtitle}</p>' if slide.subtitle else ''}
            <div class="animate-width" style="width: 60px; height: 4px; background-color: {content.accent_color}; margin-top: 20px; border-radius: 2px; animation-delay: 0.4s;"></div>
        </div>
        """
        
        slides_html += '<div style="flex: 1; display: flex; flex-direction: column; justify-content: flex-start; overflow: hidden; margin-top: 20px;">'
        
        if is_content_list:
            # Full width content list
            slides_html += '<div style="display: flex; flex-direction: column; gap: 20px; overflow-y: auto; padding-right: 10px;">'
            for item in slide.content:
                title = item.title if hasattr(item, "title") else (item.get("title", "") if isinstance(item, dict) else str(item))
                desc = item.description if hasattr(item, "description") else (item.get("description", "") if isinstance(item, dict) else "")
                title = _safe_text(title)
                desc = _safe_text(desc)
                if title or desc:
                    slides_html += f"""
                    <div class="vibe-card animate-fade-up" style="background: white; padding: 25px; border-radius: 16px; box-shadow: 0 4px 20px rgba(0,0,0,0.03); border-left: 4px solid {content.theme_color};">
                        <h4 style="color: #1e293b; font-size: 1.3em; font-weight: 700; margin-bottom: 10px; margin-top: 0;">{title}</h4>
                        <p style="color: #475569; font-size: 0.95em; line-height: 1.6; margin: 0;">{desc}</p>
                    </div>
                    """
            slides_html += '</div>'
            
        elif is_timeline:
            slides_html += '<div style="display: flex; flex-direction: column; gap: 15px; overflow-y: auto; padding: 10px 20px 10px 10px;">'
            for idx, item in enumerate(slide.content):
                title = item.title if hasattr(item, "title") else (item.get("title", "") if isinstance(item, dict) else str(item))
                desc = item.description if hasattr(item, "description") else (item.get("description", "") if isinstance(item, dict) else "")
                title = _safe_text(title)
                desc = _safe_text(desc)
                if title or desc:
                    slides_html += f"""
                    <div style="display: flex; align-items: flex-start; gap: 20px;">
                        <div class="animate-scale" style="display: flex; flex-direction: column; align-items: center; margin-top: 5px; animation-delay: {0.5 + idx*0.1}s;">
                            <div style="width: 32px; height: 32px; border-radius: 50%; background: {content.accent_color}; color: white; display: flex; align-items: center; justify-content: center; font-weight: bold; font-size: 0.8em; box-shadow: 0 0 15px {content.accent_color}66;">{idx+1}</div>
                            {f'<div style="width: 2px; height: 50px; background: linear-gradient(to bottom, {content.accent_color}, transparent); margin-top: 5px;"></div>' if idx < len(slide.content)-1 else ''}
                        </div>
                        <div class="vibe-card animate-fade-right" style="flex: 1; background: white; padding: 20px 25px; border-radius: 12px; box-shadow: 0 4px 15px rgba(0,0,0,0.02); margin-bottom: {0 if idx == len(slide.content)-1 else 10}px; animation-delay: {0.6 + idx*0.1}s;">
                            <h4 style="color: {content.theme_color}; font-size: 1.2em; font-weight: 700; margin-top: 0; margin-bottom: 8px;">{title}</h4>
                            <p style="color: #475569; font-size: 0.9em; line-height: 1.5; margin: 0;">{desc}</p>
                        </div>
                    </div>
                    """
            slides_html += '</div>'
            
        else: # cards layout
            grid_cols = "repeat(2, 1fr)" if len(slide.content) <= 4 else "repeat(3, 1fr)"
            slides_html += f'<div style="display: grid; grid-template-columns: {grid_cols}; gap: 30px; overflow-y: auto; padding: 10px;">'
            for item in slide.content:
                title = item.title if hasattr(item, "title") else (item.get("title", "") if isinstance(item, dict) else str(item))
                desc = item.description if hasattr(item, "description") else (item.get("description", "") if isinstance(item, dict) else "")
                title = _safe_text(title)
                desc = _safe_text(desc)
                if title or desc:
                    slides_html += f"""
                    <div class="vibe-card animate-fade-up" style="background: white; padding: 30px; border-radius: 20px; box-shadow: 0 10px 30px rgba(0,0,0,0.04); border-top: 4px solid {content.accent_color}; display: flex; flex-direction: column; transition: transform 0.3s ease;">
                        <div style="width: 40px; height: 40px; border-radius: 10px; background: {content.theme_color}15; display: flex; align-items: center; justify-content: center; margin-bottom: 20px;">
                            <div style="width: 16px; height: 16px; border-radius: 4px; background: {content.theme_color};"></div>
                        </div>
                        <h4 style="color: #0f172a; font-size: 1.3em; font-weight: 700; margin-top: 0; margin-bottom: 15px;">{title}</h4>
                        <p style="color: #64748b; font-size: 0.9em; line-height: 1.6; margin: 0; flex: 1;">{desc}</p>
                    </div>
                    """
            slides_html += '</div>'
            
        slides_html += '</div>' # end flex:1 container
            
        slides_html += '</div></section>'

    html_template = f"""
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="utf-8">
    <title>{safe_title}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <link rel="stylesheet" href="https://fastly.jsdelivr.net/npm/reveal.js@4.5.0/dist/reset.css">
    <link rel="stylesheet" href="https://fastly.jsdelivr.net/npm/reveal.js@4.5.0/dist/reveal.css">
    <style>
        :root {{
            --r-main-font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            --r-heading-font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            --r-main-font-size: 36px;
            --r-heading-text-transform: none;
            --r-selection-background-color: {content.accent_color};
            --r-link-color: {content.theme_color};
            --r-link-color-hover: {content.accent_color};
        }}
        
        body, html {{
            width: 100%;
            height: 100%;
            margin: 0;
            padding: 0;
            background: #f1f5f9;
        }}
        
        .reveal {{
            width: 100%;
            height: 100%;
        }}
        
        /* The most critical fix for absolute positioning and flex conflicts */
        .reveal .slides section {{
            height: 100%;
            padding: 0;
            box-sizing: border-box;
            /* Force Reveal.js to treat our sections as valid blocks */
            display: block !important;
        }}
        
        /* Inner content wrappers should handle the flex layout instead of the section tag */
        .vibe-slide-inner {{
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            height: 100%;
            width: 100%;
            box-sizing: border-box;
            padding: 0 10%;
        }}
        
        .vibe-content-inner {{
            display: flex;
            flex-direction: column;
            height: 100%;
            width: 100%;
            box-sizing: border-box;
            padding: 60px 80px;
        }}
        
        /* Ensure the content container doesn't force height beyond 100% */
        .slide-content {{
            box-sizing: border-box;
            height: 100%;
        }}
        
        /* Custom scrollbar for overflow areas */
        ::-webkit-scrollbar {{
            width: 6px;
        }}
        ::-webkit-scrollbar-track {{
            background: transparent;
        }}
        ::-webkit-scrollbar-thumb {{
            background: rgba(0,0,0,0.1);
            border-radius: 10px;
        }}
        ::-webkit-scrollbar-thumb:hover {{
            background: rgba(0,0,0,0.2);
        }}

        /* Animations */
        @keyframes fadeInUp {{
            from {{ opacity: 0; transform: translateY(30px); }}
            to {{ opacity: 1; transform: translateY(0); }}
        }}
        @keyframes fadeInRight {{
            from {{ opacity: 0; transform: translateX(-30px); }}
            to {{ opacity: 1; transform: translateX(0); }}
        }}
        @keyframes scaleIn {{
            from {{ opacity: 0; transform: scale(0.9); }}
            to {{ opacity: 1; transform: scale(1); }}
        }}
        @keyframes widthGrow {{
            from {{ width: 0; }}
            to {{ width: 80px; }}
        }}

        /* Only animate when the slide is present (active) */
        .reveal .slides section.present .animate-fade-up {{
            animation: fadeInUp 0.8s cubic-bezier(0.16, 1, 0.3, 1) forwards;
        }}
        .reveal .slides section.present .animate-fade-right {{
            animation: fadeInRight 0.8s cubic-bezier(0.16, 1, 0.3, 1) forwards;
        }}
        .reveal .slides section.present .animate-scale {{
            animation: scaleIn 0.8s cubic-bezier(0.16, 1, 0.3, 1) forwards;
        }}
        .reveal .slides section.present .animate-width {{
            animation: widthGrow 1s cubic-bezier(0.16, 1, 0.3, 1) forwards;
        }}

        /* Staggered delays for cards */
        .reveal .slides section.present .vibe-card:nth-child(1) {{ animation-delay: 0.1s; }}
        .reveal .slides section.present .vibe-card:nth-child(2) {{ animation-delay: 0.2s; }}
        .reveal .slides section.present .vibe-card:nth-child(3) {{ animation-delay: 0.3s; }}
        .reveal .slides section.present .vibe-card:nth-child(4) {{ animation-delay: 0.4s; }}
        .reveal .slides section.present .vibe-card:nth-child(5) {{ animation-delay: 0.5s; }}
        .reveal .slides section.present .vibe-card:nth-child(6) {{ animation-delay: 0.6s; }}

        /* Initial state for animated elements - set to opacity 0 ONLY if animation is supported */
        .animate-fade-up, .animate-fade-right, .animate-scale, .vibe-card {{
            opacity: 0;
        }}

        /* Fullscreen button styling */
        .fullscreen-btn {{
            position: fixed;
            top: 20px;
            right: 20px;
            z-index: 1000;
            background: rgba(0, 0, 0, 0.3);
            color: white;
            border: none;
            border-radius: 50%;
            width: 40px;
            height: 40px;
            display: flex;
            align-items: center;
            justify-content: center;
            cursor: pointer;
            transition: all 0.3s ease;
            backdrop-filter: blur(5px);
            box-shadow: 0 4px 15px rgba(0,0,0,0.1);
        }}
        .fullscreen-btn:hover {{
            background: rgba(0, 0, 0, 0.6);
            transform: scale(1.1);
        }}
        .fullscreen-btn svg {{
            width: 24px;
            height: 24px;
            fill: currentColor;
        }}
    </style>
</head>
<body>
    <button class="fullscreen-btn" id="fs-btn" title="Toggle Fullscreen">
        <svg viewBox="0 0 24 24" id="fs-icon-enter">
            <path d="M7 14H5v5h5v-2H7v-3zm-2-4h2V7h3V5H5v5zm12 7h-3v2h5v-5h-2v3zM14 5v2h3v3h2V5h-5z"/>
        </svg>
        <svg viewBox="0 0 24 24" id="fs-icon-exit" style="display: none;">
            <path d="M5 16h3v3h2v-5H5v2zm3-8H5v2h5V5H8v3zm6 11h2v-3h3v-2h-5v5zm2-11V5h-2v5h5V8h-3z"/>
        </svg>
    </button>
    <div class="reveal">
        <div class="slides">
            {slides_html}
        </div>
    </div>
    <script src="https://fastly.jsdelivr.net/npm/reveal.js@4.5.0/dist/reveal.js"></script>
    <script>
        // Use an event listener to ensure DOM is ready before init
        document.addEventListener('DOMContentLoaded', function() {{
            // Extremely resilient reveal init settings for standalone HTML files
            Reveal.initialize({{
                width: 1280,
                height: 720,
                margin: 0,
                minScale: 0.1,
                maxScale: 3.0,
                hash: true,
                center: true, // Let Reveal.js handle the centering
                transition: 'slide',
                backgroundTransition: 'slide',
                controls: true,
                controlsTutorial: true,
                progress: true,
                mouseWheel: true,
                keyboard: true,
                disableLayout: false,
                display: 'block' // Re-added display: block to prevent Flexbox collapse on init
            }}).then(() => {{
                // Fallback timeout layout recalculation to fix delayed rendering bugs
                setTimeout(() => {{
                    Reveal.layout();
                }}, 100);
                
                // Safety check: If after 2 seconds elements are still invisible (animation failed), force show them
                setTimeout(() => {{
                    document.querySelectorAll('.animate-fade-up, .animate-fade-right, .animate-scale, .vibe-card').forEach(el => {{
                        el.style.opacity = '1';
                        el.style.transform = 'none';
                    }});
                }}, 2500);
            }});
            
            // Fullscreen Logic
            const fsBtn = document.getElementById('fs-btn');
            const iconEnter = document.getElementById('fs-icon-enter');
            const iconExit = document.getElementById('fs-icon-exit');

            function toggleFullScreen() {{
                if (!document.fullscreenElement && !document.mozFullScreenElement && !document.webkitFullscreenElement && !document.msFullscreenElement) {{
                    if (document.documentElement.requestFullscreen) {{
                        document.documentElement.requestFullscreen();
                    }} else if (document.documentElement.msRequestFullscreen) {{
                        document.documentElement.msRequestFullscreen();
                    }} else if (document.documentElement.mozRequestFullScreen) {{
                        document.documentElement.mozRequestFullScreen();
                    }} else if (document.documentElement.webkitRequestFullscreen) {{
                        document.documentElement.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);
                    }}
                }} else {{
                    if (document.exitFullscreen) {{
                        document.exitFullscreen();
                    }} else if (document.msExitFullscreen) {{
                        document.msExitFullscreen();
                    }} else if (document.mozCancelFullScreen) {{
                        document.mozCancelFullScreen();
                    }} else if (document.webkitExitFullscreen) {{
                        document.webkitExitFullscreen();
                    }}
                }}
            }}

            function updateFsIcon() {{
                if (document.fullscreenElement || document.mozFullScreenElement || document.webkitFullscreenElement || document.msFullscreenElement) {{
                    iconEnter.style.display = 'none';
                    iconExit.style.display = 'block';
                }} else {{
                    iconEnter.style.display = 'block';
                    iconExit.style.display = 'none';
                }}
                // Force layout recalculation when toggling fullscreen
                setTimeout(() => Reveal.layout(), 100);
            }}

            fsBtn.addEventListener('click', toggleFullScreen);
            document.addEventListener('fullscreenchange', updateFsIcon);
            document.addEventListener('webkitfullscreenchange', updateFsIcon);
            document.addEventListener('mozfullscreenchange', updateFsIcon);
            document.addEventListener('MSFullscreenChange', updateFsIcon);
        }});
    </script>
</body>
</html>
    """
    
    filename = f"presentation_{uuid.uuid4()}.html"
    output_dir = os.path.join(os.getcwd(), "backend", "generated_ppts")
    os.makedirs(output_dir, exist_ok=True)
    file_path = os.path.join(output_dir, filename)
    
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(html_template)
        
    return filename
