from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN
from pptx.enum.shapes import MSO_SHAPE
from ..schemas import PPTContent
import os
import uuid

def hex_to_rgb(hex_color):
    hex_color = hex_color.lstrip('#')
    return RGBColor(int(hex_color[0:2], 16), int(hex_color[2:4], 16), int(hex_color[4:6], 16))

def create_pptx(content: PPTContent) -> str:
    prs = Presentation()
    
    # Standard 16:9 ratio
    prs.slide_width = Inches(13.333)
    prs.slide_height = Inches(7.5)

    # Define colors
    try:
        main_color = hex_to_rgb(content.theme_color)
        acc_color = hex_to_rgb(content.accent_color)
    except:
        main_color = hex_to_rgb("#E88E2E")
        acc_color = hex_to_rgb("#FFD700")
        
    # 1. Title Slide
    slide_layout = prs.slide_layouts[6] # Blank layout for full customization
    slide = prs.slides.add_slide(slide_layout)
    
    # Background color
    background = slide.background
    fill = background.fill
    fill.solid()
    fill.fore_color.rgb = main_color
    
    # Add title
    title_box = slide.shapes.add_textbox(Inches(1), Inches(2.5), Inches(11.333), Inches(1.5))
    tf = title_box.text_frame
    tf.text = content.title
    p = tf.paragraphs[0]
    p.alignment = PP_ALIGN.CENTER
    p.font.size = Pt(54)
    p.font.bold = True
    p.font.color.rgb = RGBColor(255, 255, 255)
    
    # Add decorative line
    line = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, Inches(5.666), Inches(4.2), Inches(2), Inches(0.05))
    line.fill.solid()
    line.fill.fore_color.rgb = acc_color
    line.line.visible = False

    # Add subtitle
    sub_box = slide.shapes.add_textbox(Inches(1), Inches(4.5), Inches(11.333), Inches(1))
    stf = sub_box.text_frame
    stf.text = "Generated by GenPPT AI Designer"
    sp = stf.paragraphs[0]
    sp.alignment = PP_ALIGN.CENTER
    sp.font.size = Pt(20)
    sp.font.color.rgb = RGBColor(240, 240, 240)

    # 2. Content Slides
    for slide_data in content.slides:
        slide = prs.slides.add_slide(prs.slide_layouts[6]) # Blank layout
        
        # Add a thick top border matching theme color (like the preview)
        top_border = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, 0, 0, prs.slide_width, Inches(0.1))
        top_border.fill.solid()
        top_border.fill.fore_color.rgb = main_color
        top_border.line.visible = False

        # Set title
        title_box = slide.shapes.add_textbox(Inches(0.8), Inches(0.5), Inches(11.7), Inches(1))
        tf = title_box.text_frame
        tf.text = slide_data.page_title
        p = tf.paragraphs[0]
        p.font.size = Pt(36)
        p.font.bold = True
        p.font.color.rgb = main_color
        
        if slide_data.layout_type == 'centered':
            p.alignment = PP_ALIGN.CENTER
            content_box = slide.shapes.add_textbox(Inches(1.5), Inches(2), Inches(10.333), Inches(4))
            ctf = content_box.text_frame
            ctf.word_wrap = True
            for point in slide_data.content:
                cp = ctf.add_paragraph()
                cp.text = point
                cp.alignment = PP_ALIGN.CENTER
                cp.font.size = Pt(24)
                cp.space_before = Pt(10)
        
        elif slide_data.layout_type == 'two_columns':
            # Left column: text
            left_box = slide.shapes.add_textbox(Inches(0.8), Inches(1.8), Inches(5.5), Inches(4.5))
            ltf = left_box.text_frame
            ltf.word_wrap = True
            for point in slide_data.content:
                lp = ltf.add_paragraph()
                lp.text = f"• {point}"
                lp.font.size = Pt(20)
                lp.space_before = Pt(10)
            
            # Right column: visual placeholder
            right_rect = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, Inches(7), Inches(1.8), Inches(5.5), Inches(4.5))
            right_rect.fill.solid()
            right_rect.fill.fore_color.rgb = RGBColor(245, 245, 245)
            right_rect.line.color.rgb = RGBColor(220, 220, 220)
            right_rect.line.width = Pt(1)
            
            if slide_data.image_description:
                img_text_box = slide.shapes.add_textbox(Inches(7.2), Inches(2.5), Inches(5.1), Inches(3))
                itf = img_text_box.text_frame
                itf.word_wrap = True
                itf.text = f"[Visual Placeholder]\n{slide_data.image_description}"
                ip = itf.paragraphs[0]
                ip.alignment = PP_ALIGN.CENTER
                ip.font.size = Pt(14)
                ip.font.italic = True
                ip.font.color.rgb = RGBColor(150, 150, 150)

        else: # Default bullet points
            content_box = slide.shapes.add_textbox(Inches(0.8), Inches(1.8), Inches(11.7), Inches(4.5))
            ctf = content_box.text_frame
            ctf.word_wrap = True
            for point in slide_data.content:
                cp = ctf.add_paragraph()
                cp.text = f"• {point}"
                cp.font.size = Pt(22)
                cp.space_before = Pt(12)
                cp.font.color.rgb = RGBColor(60, 60, 60)

        # Add visual suggestions at bottom (like the preview)
        if slide_data.image_description and slide_data.layout_type != 'two_columns':
            sug_box = slide.shapes.add_textbox(Inches(0.8), Inches(6.5), Inches(11.7), Inches(0.5))
            stf = sug_box.text_frame
            stf.text = f"🎨 Visual Suggestion: {slide_data.image_description}"
            sp = stf.paragraphs[0]
            sp.font.size = Pt(10)
            sp.font.italic = True
            sp.font.color.rgb = RGBColor(180, 180, 180)
            
            # Left accent line
            line = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, Inches(0.8), Inches(6.5), Inches(0.03), Inches(0.4))
            line.fill.solid()
            line.fill.fore_color.rgb = acc_color
            line.line.visible = False

    # Save file
    filename = f"presentation_{uuid.uuid4()}.pptx"
    output_dir = os.path.join(os.getcwd(), "backend", "generated_ppts")
    os.makedirs(output_dir, exist_ok=True)
    file_path = os.path.join(output_dir, filename)
    
    prs.save(file_path)
    return filename
