import { useEffect, useRef } from 'react';
import Reveal from 'reveal.js';
import 'reveal.js/reveal.css';
import 'reveal.js/theme/white.css';

interface Slide {
  page_title: string;
  content: string[];
  layout_type: string;
  image_description?: string;
}

interface PreviewProps {
  slides: Slide[];
  title: string;
  themeColor?: string;
  accentColor?: string;
}

export function Preview({ slides, title, themeColor = "#E88E2E", accentColor = "#FFD700" }: PreviewProps) {
  const deckRef = useRef<HTMLDivElement>(null);
  const revealInstance = useRef<Reveal.Api | null>(null);

  useEffect(() => {
    // If deckRef.current exists, initialize Reveal.js
    if (deckRef.current) {
      // If an instance already exists, destroy it before creating a new one
      if (revealInstance.current) {
        revealInstance.current.destroy();
        revealInstance.current = null;
      }
      
      revealInstance.current = new Reveal(deckRef.current, {
        embedded: true,
        controls: true,
        progress: true,
        center: true,
        width: 1200,
        height: 800,
        margin: 0.05,
        minScale: 0.2,
        maxScale: 2.0,
        hash: false, // Set to false for better embedded behavior
        transition: 'slide',
        mouseWheel: true, // Enable mouse wheel navigation
      });
      
      revealInstance.current.initialize().catch(err => {
        console.error("Reveal.js initialization error:", err);
      });
    }

    return () => {
      if (revealInstance.current) {
        try {
          revealInstance.current.destroy();
        } catch (e) {
          console.error("Error destroying Reveal.js:", e);
        }
        revealInstance.current = null;
      }
    };
  }, [slides, title]); // Re-initialize when slides or title changes

  // Add defensive check for slides
  if (!Array.isArray(slides)) {
    return <div className="p-8 text-center text-red-500 bg-red-50 rounded-lg">Invalid slides data structure</div>;
  }

  return (
    <div className="reveal" ref={deckRef} style={{ height: '500px', width: '100%', border: `4px solid ${themeColor}`, borderRadius: '12px' }}>
      <div className="slides">
        {/* Title Slide */}
        <section style={{ backgroundColor: themeColor, color: '#fff' }}>
          <h2 className="text-5xl font-bold mb-6 drop-shadow-md" style={{ color: '#fff' }}>{title || "Untitled PPT"}</h2>
          <div style={{ width: '80px', height: '4px', backgroundColor: accentColor, margin: '0 auto 24px' }}></div>
          <p className="text-xl opacity-80">Generated by GenPPT AI Designer</p>
        </section>
        
        {slides.map((slide, index) => {
          const isCentered = slide.layout_type === 'centered';
          const isTwoColumns = slide.layout_type === 'two_columns';
          
          return (
            <section key={index} className="text-left px-16 h-full flex flex-col justify-start pt-16 pb-12">
              <h3 className={`text-4xl font-bold mb-10 ${isCentered ? 'text-center' : ''}`} style={{ color: themeColor, lineHeight: '1.2' }}>
                {slide?.page_title || "Untitled Slide"}
              </h3>
              
              <div className="flex-1 flex flex-col justify-start overflow-hidden">
                <div className={`${isTwoColumns ? 'grid grid-cols-2 gap-12' : ''} ${isCentered ? 'flex flex-col items-center mt-8' : ''}`}>
                  <ul className={`space-y-6 text-2xl ${isCentered ? 'text-center list-none' : 'list-disc ml-8'} ${isTwoColumns ? 'text-xl' : ''}`}>
                    {Array.isArray(slide?.content) ? slide.content.map((point, idx) => (
                      <li key={idx} className="text-gray-800 leading-relaxed font-medium">
                        {point}
                      </li>
                    )) : (
                      <li className="list-none italic text-gray-400">No content</li>
                    )}
                  </ul>
                  
                  {isTwoColumns && slide.image_description && (
                    <div className="bg-gray-50 p-8 rounded-2xl border-2 border-dashed border-gray-200 flex items-center justify-center text-center h-80">
                      <p className="text-base text-gray-400 italic">
                         <span className="text-2xl mb-2 block">🖼️</span>
                         [视觉占位符]<br/>
                         {slide.image_description}
                      </p>
                    </div>
                  )}
                </div>
              </div>

              {!isTwoColumns && slide.image_description && (
                <div className="mt-auto p-4 bg-gray-50/50 rounded-xl text-sm text-gray-500 italic border-l-4 shadow-sm" style={{ borderColor: accentColor }}>
                  <span className="font-bold mr-2">🎨 设计建议:</span> {slide.image_description}
                </div>
              )}
            </section>
          );
        })}
      </div>
    </div>
  );
}
